name: Build Windows EXE (No Excel)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # 안정권

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_noxl.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --name ConcretePumping_NoExcel app_noxl.py

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: ConcretePumping_NoExcel
          path: dist/ConcretePumping_NoExcel.exe
